name: Build

on:
  pull_request:
    branches: [ 1-3 ]
  push:
    branches: [ 1-3 ]
  schedule:
    - cron: "0 10 * * *"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print rustc version
        run: rustc --version
      - name: Install wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: Install apt packages
        run: sudo apt install -y libzmq3-dev
      - name: Install Just
        run: sudo snap install --edge --classic just
      - name: Install protoc
        run: |
          curl -OLsS https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
          unzip protoc-3.5.1-linux-x86_64.zip -d protoc3
          rm protoc-3.5.1-linux-x86_64.zip
      - name: Lint
        run: PATH=$PATH:$(pwd)/protoc3/bin just lint
      - name: Build
        run: PATH=$PATH:$(pwd)/protoc3/bin just build
      - name: Test
        run: PATH=$PATH:$(pwd)/protoc3/bin just test
